"""okx_py 原生扩展模块类型存根。

说明：该模块由 PyO3 生成；为保证 IDE 补全与接口发现性，存根以 `Any` 作为统一类型出口。
"""

from __future__ import annotations

from typing import Any, final

__version__: str
__all__: list[str]
__all__ = ['__version__', 'Credentials', 'Config', 'OkxClient', 'AsyncOkxClient', 'WsClient', 'Balance', 'BalanceDetail', 'Position', 'Order', 'Ticker']

@final
class Credentials:
    def __new__(cls, /, api_key, secret_key, passphrase) -> "Credentials": ...
    def __init__(self, /) -> None: ...


@final
class Config:
    simulated: bool
    rest_url: str

    def __new__(cls, /, credentials, simulated=False, timeout_secs=30) -> "Config": ...
    def __init__(self, /) -> None: ...


@final
class OkxClient:
    def __new__(cls, /, config) -> "OkxClient": ...
    def __init__(self, /) -> None: ...

    def activate_option(self, /) -> Any: ...
    def adjustment_margin(self, /, inst_id, pos_side, type_, amt, loan_trans=None) -> Any: ...
    def amend_algo_order(self, /, inst_id=None, algo_id=None, algo_cl_ord_id=None, cxl_on_fail=None, req_id=None, new_sz=None, new_tp_trigger_px=None, new_tp_ord_px=None, new_sl_trigger_px=None, new_sl_ord_px=None, new_tp_trigger_px_type=None, new_sl_trigger_px_type=None) -> Any: ...
    def amend_batch_orders(self, /, orders) -> Any: ...
    def amend_fix_loan_borrowing_order(self, /, ord_id=None, reborrow=None, renew_max_rate=None) -> Any: ...
    def amend_leading_instruments(self, /, request_json) -> Any: ...
    def amend_order(self, /, inst_id, ord_id=None, cl_ord_id=None, req_id=None, new_sz=None, new_px=None, new_tp_trigger_px=None, new_tp_ord_px=None, new_sl_trigger_px=None, new_sl_ord_px=None, new_tp_trigger_px_type=None, new_sl_trigger_px_type=None) -> Any: ...
    def amend_recurring_buy_order(self, /, payload_json) -> Any: ...
    def borrow_repay(self, /, ccy=None, side=None, amt=None, ord_id=None) -> Any: ...
    def cancel_algo_orders(self, /, requests) -> Any: ...
    def cancel_all_after(self, /, request_json) -> Any: ...
    def cancel_all_quotes(self, /, request_json) -> Any: ...
    def cancel_all_rfqs(self, /, request_json) -> Any: ...
    def cancel_batch_orders(self, /, orders) -> Any: ...
    def cancel_batch_quotes(self, /, request_json) -> Any: ...
    def cancel_batch_rfqs(self, /, request_json) -> Any: ...
    def cancel_order(self, /, inst_id, ord_id=None, cl_ord_id=None) -> Any: ...
    def cancel_quote(self, /, request_json) -> Any: ...
    def cancel_rfq(self, /, request_json) -> Any: ...
    def cancel_withdrawal(self, /, wd_id=None) -> Any: ...
    def close_lead_position(self, /, request_json) -> Any: ...
    def close_position(self, /, inst_id, mgn_mode, pos_side=None, ccy=None, auto_cancel=None, cl_ord_id=None, tag=None) -> Any: ...
    def convert_dust_assets(self, /, ccy) -> Any: ...
    def convert_trade(self, /, quote_id, base_ccy, quote_ccy, side, sz, sz_ccy, tag=None) -> Any: ...
    def create_quote(self, /, request_json) -> Any: ...
    def create_rfq(self, /, request_json) -> Any: ...
    def defi_cancel(self, /, request_json) -> Any: ...
    def defi_get_offers(self, /, params_json=None) -> Any: ...
    def defi_orders_active(self, /, params_json=None) -> Any: ...
    def defi_orders_history(self, /, params_json=None) -> Any: ...
    def defi_purchase(self, /, request_json) -> Any: ...
    def defi_redeem(self, /, request_json) -> Any: ...
    def easy_convert(self, /, from_ccy, to_ccy) -> Any: ...
    def estimate_convert_quote(self, /, base_ccy, quote_ccy, side, rfq_sz, rfq_sz_ccy=None, tag=None) -> Any: ...
    def execute_quote(self, /, request_json) -> Any: ...
    def fd_get_rebate_per_orders(self, /, params_json) -> Any: ...
    def fd_rebate_per_orders(self, /, params_json) -> Any: ...
    def fix_loan_manual_reborrow(self, /, ord_id=None, max_rate=None) -> Any: ...
    def funds_transfer(self, /, ccy, amt, from_account, to_account, transfer_type=None, sub_acct=None, inst_id=None, to_inst_id=None, loan_trans=None) -> Any: ...
    def get_account_bills(self, /, inst_type=None, ccy=None, mgn_mode=None, ct_type=None, type_=None, sub_type=None, after=None, before=None, limit=None) -> Any: ...
    def get_account_bills_archive(self, /, inst_type=None, ccy=None, mgn_mode=None, ct_type=None, type_=None, sub_type=None, after=None, before=None, limit=None, begin=None, end=None) -> Any: ...
    def get_account_config(self, /) -> Any: ...
    def get_account_position_risk(self, /) -> Any: ...
    def get_account_position_tiers(self, /, inst_type, uly, inst_family) -> Any: ...
    def get_affiliate_rebate_info(self, /, api_key) -> Any: ...
    def get_algo_order_details(self, /, algo_id=None, algo_cl_ord_id=None) -> Any: ...
    def get_algo_orders_history(self, /, ord_type, state=None, algo_id=None, inst_type=None, inst_id=None, after=None, before=None, limit=None) -> Any: ...
    def get_algo_orders_pending(self, /, ord_type, algo_id=None, inst_type=None, inst_id=None, after=None, before=None, limit=None) -> Any: ...
    def get_asset_balances(self, /, ccy=None) -> Any: ...
    def get_asset_valuation(self, /, ccy=None) -> Any: ...
    def get_balance(self, /, ccy=None) -> Any: ...
    def get_block_rfq_trades(self, /, params_json=None) -> Any: ...
    def get_block_ticker(self, /, inst_id) -> Any: ...
    def get_block_tickers(self, /, inst_type, uly=None, inst_family=None) -> Any: ...
    def get_block_trades(self, /, inst_id) -> Any: ...
    def get_borrow_repay_history(self, /, ccy=None, after=None, before=None, limit=None) -> Any: ...
    def get_candles(self, /, inst_id, bar=None, after=None, before=None, limit=None) -> Any: ...
    def get_contracts_open_interest_volume(self, /, params_json=None) -> Any: ...
    def get_convert_contract_coin(self, /, inst_id, sz, px=None, unit=None, op_type=None) -> Any: ...
    def get_convert_currencies(self, /) -> Any: ...
    def get_convert_currency_pair(self, /, from_ccy, to_ccy) -> Any: ...
    def get_convert_history(self, /, after=None, before=None, limit=None, tag=None) -> Any: ...
    def get_counterparties(self, /) -> Any: ...
    def get_currencies(self, /, ccy=None) -> Any: ...
    def get_delivery_exercise_history(self, /, inst_type, uly=None, inst_family=None, after=None, before=None, limit=None) -> Any: ...
    def get_deposit_address(self, /, ccy) -> Any: ...
    def get_deposit_history(self, /, ccy=None, dep_id=None, tx_id=None, record_type=None, state=None, after=None, before=None, limit=None) -> Any: ...
    def get_deposit_lightning(self, /, ccy, amt, to) -> Any: ...
    def get_deposit_withdraw_status(self, /, wd_id=None, tx_id=None, ccy=None, to=None, chain=None) -> Any: ...
    def get_discount_interest_free_quota(self, /, ccy=None) -> Any: ...
    def get_easy_convert_currency_list(self, /) -> Any: ...
    def get_easy_convert_history(self, /, after=None, before=None, limit=None) -> Any: ...
    def get_entrust_subaccount_list(self, /, sub_acct=None) -> Any: ...
    def get_estimated_price(self, /, inst_id) -> Any: ...
    def get_existing_lead_positions(self, /, params_json=None) -> Any: ...
    def get_fee_rates(self, /, inst_type, inst_id=None, uly=None, inst_family=None) -> Any: ...
    def get_fills(self, /, inst_type=None, uly=None, inst_family=None, inst_id=None, ord_id=None, after=None, before=None, begin=None, end=None, limit=None) -> Any: ...
    def get_fills_history(self, /, inst_type, uly=None, inst_family=None, inst_id=None, ord_id=None, after=None, before=None, limit=None) -> Any: ...
    def get_fix_loan_borrowing_limit(self, /) -> Any: ...
    def get_fix_loan_borrowing_orders_list(self, /, ord_id=None, ccy=None, state=None, after=None, before=None, limit=None) -> Any: ...
    def get_fix_loan_borrowing_quote(self, /, type_=None, ccy=None, amt=None, max_rate=None, term=None, ord_id=None) -> Any: ...
    def get_funding_bills(self, /, ccy=None, type_=None, after=None, before=None, limit=None) -> Any: ...
    def get_funding_rate(self, /, inst_id) -> Any: ...
    def get_funding_rate_history(self, /, inst_id, after=None, before=None, limit=None) -> Any: ...
    def get_greeks(self, /, ccy=None) -> Any: ...
    def get_history_candles(self, /, inst_id, bar=None, after=None, before=None, limit=None) -> Any: ...
    def get_history_trades(self, /, inst_id, trade_type=None, after=None, before=None, limit=None) -> Any: ...
    def get_index_candles(self, /, inst_id, bar=None, after=None, before=None, limit=None) -> Any: ...
    def get_index_tickers(self, /, quote_ccy=None, inst_id=None) -> Any: ...
    def get_instruments(self, /, inst_type, inst_id=None) -> Any: ...
    def get_insurance_fund(self, /, inst_type=None, type_=None, uly=None, ccy=None, before=None, after=None, limit=None, inst_family=None) -> Any: ...
    def get_interest_accrued(self, /, inst_id=None, ccy=None, mgn_mode=None, after=None, before=None, limit=None) -> Any: ...
    def get_interest_limits(self, /, type_=None, ccy=None) -> Any: ...
    def get_interest_rate(self, /, ccy=None) -> Any: ...
    def get_interest_rate_loan_quota(self, /) -> Any: ...
    def get_interest_volume_strike(self, /, params_json=None) -> Any: ...
    def get_lead_position_history(self, /, params_json=None) -> Any: ...
    def get_leading_instruments(self, /, params_json=None) -> Any: ...
    def get_lending_history(self, /, ccy=None, after=None, before=None, limit=None) -> Any: ...
    def get_lending_rate_history(self, /, ccy=None, after=None, before=None, limit=None) -> Any: ...
    def get_lending_rate_summary(self, /, ccy=None) -> Any: ...
    def get_leverage_info(self, /, mgn_mode, ccy=None, inst_id=None) -> Any: ...
    def get_long_short_ratio(self, /, params_json=None) -> Any: ...
    def get_margin_lending_ratio(self, /, params_json=None) -> Any: ...
    def get_mark_price(self, /, inst_type, uly=None, inst_family=None, inst_id=None) -> Any: ...
    def get_mark_price_candles(self, /, inst_id, bar=None, after=None, before=None, limit=None) -> Any: ...
    def get_max_avail_size(self, /, inst_id, td_mode, ccy=None, reduce_only=None, quick_mgn_type=None) -> Any: ...
    def get_max_loan(self, /, inst_id, mgn_mode, mgn_ccy=None) -> Any: ...
    def get_max_size(self, /, inst_id, td_mode, ccy=None, px=None, leverage=None) -> Any: ...
    def get_max_withdrawal(self, /, ccy=None) -> Any: ...
    def get_mmp_config(self, /) -> Any: ...
    def get_non_tradable_assets(self, /, ccy=None) -> Any: ...
    def get_one_click_repay_currency_list(self, /) -> Any: ...
    def get_one_click_repay_history(self, /, after=None, before=None, limit=None) -> Any: ...
    def get_open_interest(self, /, inst_type, uly=None, inst_id=None, inst_family=None) -> Any: ...
    def get_open_interest_volume_expiry(self, /, params_json=None) -> Any: ...
    def get_opt_summary(self, /, uly=None, exp_time=None, inst_family=None) -> Any: ...
    def get_option_family_trades(self, /, inst_family) -> Any: ...
    def get_options_open_interest_volume(self, /, params_json=None) -> Any: ...
    def get_order(self, /, inst_id, ord_id=None, cl_ord_id=None) -> Any: ...
    def get_orderbook(self, /, inst_id, depth=None) -> Any: ...
    def get_orderbook_lite(self, /, inst_id) -> Any: ...
    def get_orders_history(self, /, inst_type, uly=None, inst_family=None, inst_id=None, ord_type=None, state=None, category=None, after=None, before=None, begin=None, end=None, limit=None) -> Any: ...
    def get_orders_history_archive(self, /, inst_type, uly=None, inst_family=None, inst_id=None, ord_type=None, state=None, category=None, after=None, before=None, begin=None, end=None, limit=None) -> Any: ...
    def get_orders_pending(self, /, inst_type=None, inst_id=None) -> Any: ...
    def get_position_tiers(self, /, inst_type, td_mode, uly=None, inst_id=None, ccy=None, tier=None, inst_family=None) -> Any: ...
    def get_positions(self, /, inst_type=None, inst_id=None) -> Any: ...
    def get_positions_history(self, /, inst_type=None, inst_id=None, mgn_mode=None, type_=None, pos_id=None, after=None, before=None, limit=None) -> Any: ...
    def get_price_limit(self, /, inst_id) -> Any: ...
    def get_profit_sharing_details(self, /, params_json=None) -> Any: ...
    def get_public_trades(self, /, params_json=None) -> Any: ...
    def get_put_call_ratio(self, /, params_json=None) -> Any: ...
    def get_quote_products(self, /, params_json=None) -> Any: ...
    def get_quotes(self, /, params_json=None) -> Any: ...
    def get_recurring_buy_order_details(self, /, params_json) -> Any: ...
    def get_recurring_buy_order_history(self, /, params_json=None) -> Any: ...
    def get_recurring_buy_order_list(self, /, params_json=None) -> Any: ...
    def get_recurring_buy_sub_orders(self, /, params_json) -> Any: ...
    def get_rfqs(self, /, params_json=None) -> Any: ...
    def get_saving_balance(self, /, ccy=None) -> Any: ...
    def get_simulated_margin(self, /, inst_type, incl_real_pos=None, spot_offset_type=None, sim_pos_json=None) -> Any: ...
    def get_sub_account_borrow_interest_and_limit(self, /, sub_acct=None, ccy=None) -> Any: ...
    def get_subaccount_balance(self, /, sub_acct) -> Any: ...
    def get_subaccount_bills(self, /, ccy=None, bill_type=None, sub_acct=None, after=None, before=None, limit=None) -> Any: ...
    def get_subaccount_funding_balance(self, /, sub_acct, ccy=None) -> Any: ...
    def get_subaccount_list(self, /, enable=None, sub_acct=None, after=None, before=None, limit=None) -> Any: ...
    def get_support_coin(self, /) -> Any: ...
    def get_system_status(self, /, state=None) -> Any: ...
    def get_system_time(self, /) -> Any: ...
    def get_taker_flow(self, /, params_json=None) -> Any: ...
    def get_taker_volume(self, /, params_json=None) -> Any: ...
    def get_ticker(self, /, inst_id) -> Any: ...
    def get_tickers(self, /, inst_type, uly=None, inst_family=None) -> Any: ...
    def get_total_profit_sharing(self, /) -> Any: ...
    def get_trades(self, /, inst_id, limit=None) -> Any: ...
    def get_transfer_state(self, /, trans_id, type_) -> Any: ...
    def get_underlying(self, /, inst_type=None) -> Any: ...
    def get_unrealized_profit_sharing_details(self, /, params_json=None) -> Any: ...
    def get_vip_interest_accrued(self, /, ccy=None, ord_id=None, after=None, before=None, limit=None) -> Any: ...
    def get_vip_interest_deducted(self, /, ccy=None, ord_id=None, after=None, before=None, limit=None) -> Any: ...
    def get_vip_interest_rate_loan_quota(self, /) -> Any: ...
    def get_vip_loan_order_detail(self, /, ccy=None, ord_id=None, after=None, before=None, limit=None) -> Any: ...
    def get_vip_loan_order_list(self, /, ord_id=None, state=None, ccy=None, after=None, before=None, limit=None) -> Any: ...
    def get_withdrawal_history(self, /, ccy=None, wd_id=None, client_id=None, tx_id=None, record_type=None, state=None, after=None, before=None, limit=None) -> Any: ...
    def grid_ai_param(self, /, params_json=None) -> Any: ...
    def grid_amend_order_algo(self, /, payload_json) -> Any: ...
    def grid_compute_margin_balance(self, /, payload_json) -> Any: ...
    def grid_margin_balance(self, /, payload_json) -> Any: ...
    def grid_order_algo(self, /, payload_json) -> Any: ...
    def grid_orders_algo_details(self, /, params_json) -> Any: ...
    def grid_orders_algo_history(self, /, params_json=None) -> Any: ...
    def grid_orders_algo_pending(self, /, params_json=None) -> Any: ...
    def grid_positions(self, /, params_json=None) -> Any: ...
    def grid_stop_order_algo(self, /, payload_json) -> Any: ...
    def grid_sub_orders(self, /, params_json) -> Any: ...
    def grid_withdraw_income(self, /, payload_json) -> Any: ...
    def mass_cancel(self, /, request_json) -> Any: ...
    def one_click_repay(self, /, debt_ccy, repay_ccy) -> Any: ...
    def order_precheck(self, /, request_json) -> Any: ...
    def place_algo_order(self, /, inst_id, td_mode, side, ord_type, sz, ccy=None, pos_side=None, reduce_only=None, tgt_ccy=None, algo_cl_ord_id=None, trigger_px=None, order_px=None, trigger_px_type=None, tp_trigger_px=None, tp_ord_px=None, tp_trigger_px_type=None, sl_trigger_px=None, sl_ord_px=None, sl_trigger_px_type=None, callback_ratio=None, callback_spread=None, active_px=None) -> Any: ...
    def place_batch_orders(self, /, orders) -> Any: ...
    def place_fix_loan_borrowing_order(self, /, ccy=None, amt=None, max_rate=None, term=None, reborrow=None, reborrow_rate=None) -> Any: ...
    def place_lead_stop_order(self, /, request_json) -> Any: ...
    def place_order(self, /, inst_id, td_mode, side, ord_type, sz, px=None, cl_ord_id=None) -> Any: ...
    def place_recurring_buy_order(self, /, payload_json) -> Any: ...
    def position_builder(self, /, acct_lv=None, incl_real_pos_and_eq=None, lever=None, greeks_type=None, sim_pos_json=None, sim_asset_json=None) -> Any: ...
    def purchase_redempt(self, /, ccy, amt, side, rate) -> Any: ...
    def repay_fix_loan_borrowing_order(self, /, ord_id=None) -> Any: ...
    def reset_mmp(self, /, request_json) -> Any: ...
    def reset_subaccount_apikey(self, /, sub_acct, api_key, label, perm=None, ip=None) -> Any: ...
    def saving_balance(self, /, params_json=None) -> Any: ...
    def saving_lending_history(self, /, params_json=None) -> Any: ...
    def saving_public_lending_rate(self, /, params_json=None) -> Any: ...
    def saving_purchase_redemption(self, /, request_json) -> Any: ...
    def saving_set_lending_rate(self, /, request_json) -> Any: ...
    def set_account_level(self, /, acct_lv) -> Any: ...
    def set_auto_loan(self, /, auto_loan=None) -> Any: ...
    def set_auto_repay(self, /, auto_repay=None) -> Any: ...
    def set_greeks(self, /, greeks_type) -> Any: ...
    def set_isolated_mode(self, /, iso_mode, type_) -> Any: ...
    def set_lending_rate(self, /, ccy, rate) -> Any: ...
    def set_leverage(self, /, lever, mgn_mode, inst_id=None, ccy=None, pos_side=None) -> Any: ...
    def set_marker_instrument(self, /, request_json) -> Any: ...
    def set_mmp_config(self, /, request_json) -> Any: ...
    def set_permission_transfer_out(self, /, sub_acct, can_trans_out) -> Any: ...
    def set_position_mode(self, /, pos_mode) -> Any: ...
    def set_risk_offset_type(self, /, type_) -> Any: ...
    def set_sub_accounts_vip_loan(self, /, enable, alloc_json) -> Any: ...
    def simple_earn_amend_lending_order(self, /, request_json) -> Any: ...
    def simple_earn_get_lending_apy_history(self, /, params_json=None) -> Any: ...
    def simple_earn_get_lending_offers(self, /, params_json=None) -> Any: ...
    def simple_earn_get_lending_orders_list(self, /, params_json=None) -> Any: ...
    def simple_earn_get_lending_sub_orders(self, /, params_json=None) -> Any: ...
    def simple_earn_get_pending_lending_volume(self, /, params_json=None) -> Any: ...
    def simple_earn_place_lending_order(self, /, request_json) -> Any: ...
    def spot_borrow_repay_history(self, /, ccy=None, type_=None, after=None, before=None, limit=None) -> Any: ...
    def spot_manual_borrow_repay(self, /, ccy=None, side=None, amt=None) -> Any: ...
    def spread_cancel_all_orders(self, /, payload_json) -> Any: ...
    def spread_cancel_order(self, /, payload_json) -> Any: ...
    def spread_get_active_orders(self, /, params_json=None) -> Any: ...
    def spread_get_order_book(self, /, params_json) -> Any: ...
    def spread_get_order_details(self, /, params_json) -> Any: ...
    def spread_get_orders(self, /, params_json=None) -> Any: ...
    def spread_get_public_trades(self, /, params_json) -> Any: ...
    def spread_get_spreads(self, /, params_json=None) -> Any: ...
    def spread_get_ticker(self, /, params_json) -> Any: ...
    def spread_get_trades(self, /, params_json=None) -> Any: ...
    def spread_place_order(self, /, payload_json) -> Any: ...
    def stop_recurring_buy_order(self, /, payload_json) -> Any: ...
    def subaccount_transfer(self, /, ccy, amt, froms, to, from_sub_account, to_sub_account) -> Any: ...
    def withdrawal(self, /, ccy, amt, dest, to_addr, chain=None, area_code=None, client_id=None, fee=None) -> Any: ...
    def withdrawal_lightning(self, /, ccy, invoice, memo) -> Any: ...

@final
class AsyncOkxClient:
    def __new__(cls, /, config) -> "AsyncOkxClient": ...
    def __init__(self, /) -> None: ...

    async def activate_option(self, /) -> Any: ...
    async def adjustment_margin(self, /, inst_id, pos_side, type_, amt, loan_trans=None) -> Any: ...
    async def amend_algo_order(self, /, inst_id=None, algo_id=None, algo_cl_ord_id=None, cxl_on_fail=None, req_id=None, new_sz=None, new_tp_trigger_px=None, new_tp_ord_px=None, new_sl_trigger_px=None, new_sl_ord_px=None, new_tp_trigger_px_type=None, new_sl_trigger_px_type=None) -> Any: ...
    async def amend_batch_orders(self, /, orders) -> Any: ...
    async def amend_fix_loan_borrowing_order(self, /, ord_id=None, reborrow=None, renew_max_rate=None) -> Any: ...
    async def amend_leading_instruments(self, /, request_json) -> Any: ...
    async def amend_order(self, /, inst_id, ord_id=None, cl_ord_id=None, req_id=None, new_sz=None, new_px=None, new_tp_trigger_px=None, new_tp_ord_px=None, new_sl_trigger_px=None, new_sl_ord_px=None, new_tp_trigger_px_type=None, new_sl_trigger_px_type=None) -> Any: ...
    async def amend_recurring_buy_order(self, /, payload_json) -> Any: ...
    async def borrow_repay(self, /, ccy=None, side=None, amt=None, ord_id=None) -> Any: ...
    async def cancel_algo_orders(self, /, requests) -> Any: ...
    async def cancel_all_after(self, /, request_json) -> Any: ...
    async def cancel_all_quotes(self, /, request_json) -> Any: ...
    async def cancel_all_rfqs(self, /, request_json) -> Any: ...
    async def cancel_batch_orders(self, /, orders) -> Any: ...
    async def cancel_batch_quotes(self, /, request_json) -> Any: ...
    async def cancel_batch_rfqs(self, /, request_json) -> Any: ...
    async def cancel_order(self, /, inst_id, ord_id=None, cl_ord_id=None) -> Any: ...
    async def cancel_quote(self, /, request_json) -> Any: ...
    async def cancel_rfq(self, /, request_json) -> Any: ...
    async def cancel_withdrawal(self, /, wd_id=None) -> Any: ...
    async def close_lead_position(self, /, request_json) -> Any: ...
    async def close_position(self, /, inst_id, mgn_mode, pos_side=None, ccy=None, auto_cancel=None, cl_ord_id=None, tag=None) -> Any: ...
    async def convert_dust_assets(self, /, ccy) -> Any: ...
    async def convert_trade(self, /, quote_id, base_ccy, quote_ccy, side, sz, sz_ccy, tag=None) -> Any: ...
    async def create_quote(self, /, request_json) -> Any: ...
    async def create_rfq(self, /, request_json) -> Any: ...
    async def defi_cancel(self, /, request_json) -> Any: ...
    async def defi_get_offers(self, /, params_json=None) -> Any: ...
    async def defi_orders_active(self, /, params_json=None) -> Any: ...
    async def defi_orders_history(self, /, params_json=None) -> Any: ...
    async def defi_purchase(self, /, request_json) -> Any: ...
    async def defi_redeem(self, /, request_json) -> Any: ...
    async def easy_convert(self, /, from_ccy, to_ccy) -> Any: ...
    async def estimate_convert_quote(self, /, base_ccy, quote_ccy, side, rfq_sz, rfq_sz_ccy=None, tag=None) -> Any: ...
    async def execute_quote(self, /, request_json) -> Any: ...
    async def fd_get_rebate_per_orders(self, /, params_json) -> Any: ...
    async def fd_rebate_per_orders(self, /, params_json) -> Any: ...
    async def fix_loan_manual_reborrow(self, /, ord_id=None, max_rate=None) -> Any: ...
    async def funds_transfer(self, /, ccy, amt, from_acct, to_acct, sub_acct=None, inst_id=None, to_inst_id=None) -> Any: ...
    async def get_account_bills(self, /, inst_type=None, ccy=None, mgn_mode=None, ct_type=None, type_=None, sub_type=None, after=None, before=None, limit=None) -> Any: ...
    async def get_account_bills_archive(self, /, inst_type=None, ccy=None, mgn_mode=None, ct_type=None, type_=None, sub_type=None, after=None, before=None, limit=None, begin=None, end=None) -> Any: ...
    async def get_account_config(self, /) -> Any: ...
    async def get_account_position_risk(self, /) -> Any: ...
    async def get_account_position_tiers(self, /, inst_type, uly, inst_family) -> Any: ...
    async def get_affiliate_rebate_info(self, /, api_key) -> Any: ...
    async def get_algo_order_details(self, /, algo_id=None, algo_cl_ord_id=None) -> Any: ...
    async def get_algo_orders_history(self, /, ord_type, state=None, algo_id=None, inst_type=None, inst_id=None, after=None, before=None, limit=None) -> Any: ...
    async def get_algo_orders_pending(self, /, ord_type, algo_id=None, inst_type=None, inst_id=None, after=None, before=None, limit=None) -> Any: ...
    async def get_asset_balances(self, /, ccy=None) -> Any: ...
    async def get_asset_valuation(self, /, ccy=None) -> Any: ...
    async def get_balance(self, /, ccy=None) -> Any: ...
    async def get_block_rfq_trades(self, /, params_json=None) -> Any: ...
    async def get_block_ticker(self, /, inst_id) -> Any: ...
    async def get_block_tickers(self, /, inst_type, uly=None, inst_family=None) -> Any: ...
    async def get_block_trades(self, /, inst_id) -> Any: ...
    async def get_borrow_repay_history(self, /, ccy=None, after=None, before=None, limit=None) -> Any: ...
    async def get_candles(self, /, inst_id, bar=None, after=None, before=None, limit=None) -> Any: ...
    async def get_contracts_open_interest_volume(self, /, params_json=None) -> Any: ...
    async def get_convert_contract_coin(self, /, type_=None, inst_id=None, sz=None, px=None, unit=None) -> Any: ...
    async def get_convert_currencies(self, /) -> Any: ...
    async def get_convert_currency_pair(self, /, from_ccy, to_ccy) -> Any: ...
    async def get_convert_history(self, /, after=None, before=None, limit=None, tag=None) -> Any: ...
    async def get_counterparties(self, /) -> Any: ...
    async def get_currencies(self, /, ccy=None) -> Any: ...
    async def get_delivery_exercise_history(self, /, inst_type, uly=None, inst_family=None, after=None, before=None, limit=None) -> Any: ...
    async def get_deposit_address(self, /, ccy) -> Any: ...
    async def get_deposit_history(self, /, ccy=None, dep_id=None, tx_id=None, state=None, after=None, before=None, limit=None) -> Any: ...
    async def get_deposit_lightning(self, /, ccy, amt, to) -> Any: ...
    async def get_deposit_withdraw_status(self, /, wd_id=None, tx_id=None, ccy=None, to=None, chain=None) -> Any: ...
    async def get_discount_interest_free_quota(self, /, ccy=None) -> Any: ...
    async def get_easy_convert_currency_list(self, /) -> Any: ...
    async def get_easy_convert_history(self, /, after=None, before=None, limit=None) -> Any: ...
    async def get_entrust_subaccount_list(self, /, sub_acct=None) -> Any: ...
    async def get_estimated_price(self, /, inst_id) -> Any: ...
    async def get_existing_lead_positions(self, /, params_json=None) -> Any: ...
    async def get_fee_rates(self, /, inst_type, inst_id=None, uly=None, inst_family=None) -> Any: ...
    async def get_fills(self, /, inst_type=None, uly=None, inst_family=None, inst_id=None, ord_id=None, after=None, before=None, begin=None, end=None, limit=None) -> Any: ...
    async def get_fills_history(self, /, inst_type, uly=None, inst_family=None, inst_id=None, ord_id=None, after=None, before=None, limit=None) -> Any: ...
    async def get_fix_loan_borrowing_limit(self, /) -> Any: ...
    async def get_fix_loan_borrowing_orders_list(self, /, ord_id=None, ccy=None, state=None, after=None, before=None, limit=None) -> Any: ...
    async def get_fix_loan_borrowing_quote(self, /, type_=None, ccy=None, amt=None, max_rate=None, term=None, ord_id=None) -> Any: ...
    async def get_funding_balance(self, /, ccy=None) -> Any: ...
    async def get_funding_bills(self, /, ccy=None, type_=None, after=None, before=None, limit=None) -> Any: ...
    async def get_funding_rate(self, /, inst_id) -> Any: ...
    async def get_funding_rate_history(self, /, inst_id, after=None, before=None, limit=None) -> Any: ...
    async def get_greeks(self, /, ccy=None) -> Any: ...
    async def get_history_candles(self, /, inst_id, bar=None, after=None, before=None, limit=None) -> Any: ...
    async def get_history_trades(self, /, inst_id, type=Ellipsis, after=None, before=None, limit=None) -> Any: ...
    async def get_index_candles(self, /, inst_id, bar=None, after=None, before=None, limit=None) -> Any: ...
    async def get_index_tickers(self, /, quote_ccy=None, inst_id=None) -> Any: ...
    async def get_instruments(self, /, inst_type, inst_id=None) -> Any: ...
    async def get_insurance_fund(self, /, inst_type=None, type_=None, uly=None, ccy=None, before=None, after=None, limit=None, inst_family=None) -> Any: ...
    async def get_interest_accrued(self, /, inst_id=None, ccy=None, mgn_mode=None, after=None, before=None, limit=None) -> Any: ...
    async def get_interest_limits(self, /, type_=None, ccy=None) -> Any: ...
    async def get_interest_rate(self, /, ccy=None) -> Any: ...
    async def get_interest_rate_loan_quota(self, /) -> Any: ...
    async def get_interest_volume_strike(self, /, params_json=None) -> Any: ...
    async def get_lead_position_history(self, /, params_json=None) -> Any: ...
    async def get_leading_instruments(self, /, params_json=None) -> Any: ...
    async def get_lending_history(self, /, ccy=None, after=None, before=None, limit=None) -> Any: ...
    async def get_lending_rate_history(self, /, ccy=None, after=None, before=None, limit=None) -> Any: ...
    async def get_lending_rate_summary(self, /, ccy=None) -> Any: ...
    async def get_leverage_info(self, /, mgn_mode, ccy=None, inst_id=None) -> Any: ...
    async def get_long_short_ratio(self, /, params_json=None) -> Any: ...
    async def get_margin_lending_ratio(self, /, params_json=None) -> Any: ...
    async def get_mark_price(self, /, inst_type, uly=None, inst_family=None, inst_id=None) -> Any: ...
    async def get_mark_price_candles(self, /, inst_id, bar=None, after=None, before=None, limit=None) -> Any: ...
    async def get_max_avail_size(self, /, inst_id, td_mode, ccy=None, reduce_only=None, quick_mgn_type=None) -> Any: ...
    async def get_max_loan(self, /, inst_id, mgn_mode, mgn_ccy=None) -> Any: ...
    async def get_max_size(self, /, inst_id, td_mode, ccy=None, px=None, leverage=None) -> Any: ...
    async def get_max_withdrawal(self, /, ccy=None) -> Any: ...
    async def get_mmp_config(self, /) -> Any: ...
    async def get_non_tradable_assets(self, /, ccy=None) -> Any: ...
    async def get_one_click_repay_currency_list(self, /) -> Any: ...
    async def get_one_click_repay_history(self, /, after=None, before=None, limit=None) -> Any: ...
    async def get_open_interest(self, /, inst_type, uly=None, inst_id=None, inst_family=None) -> Any: ...
    async def get_open_interest_volume_expiry(self, /, params_json=None) -> Any: ...
    async def get_opt_summary(self, /, uly=None, exp_time=None, inst_family=None) -> Any: ...
    async def get_option_family_trades(self, /, inst_family) -> Any: ...
    async def get_options_open_interest_volume(self, /, params_json=None) -> Any: ...
    async def get_order(self, /, inst_id, ord_id=None, cl_ord_id=None) -> Any: ...
    async def get_orderbook(self, /, inst_id, depth=None) -> Any: ...
    async def get_orderbook_lite(self, /, inst_id) -> Any: ...
    async def get_orders_history(self, /, inst_type, uly=None, inst_family=None, inst_id=None, ord_type=None, state=None, category=None, after=None, before=None, begin=None, end=None, limit=None) -> Any: ...
    async def get_orders_history_archive(self, /, inst_type, uly=None, inst_family=None, inst_id=None, ord_type=None, state=None, category=None, after=None, before=None, begin=None, end=None, limit=None) -> Any: ...
    async def get_orders_pending(self, /, inst_type=None, inst_id=None) -> Any: ...
    async def get_position_tiers(self, /, inst_type, td_mode, uly=None, inst_id=None, ccy=None, tier=None, inst_family=None) -> Any: ...
    async def get_positions(self, /, inst_type=None, inst_id=None) -> Any: ...
    async def get_positions_history(self, /, inst_type=None, inst_id=None, mgn_mode=None, type_=None, pos_id=None, after=None, before=None, limit=None) -> Any: ...
    async def get_price_limit(self, /, inst_id) -> Any: ...
    async def get_profit_sharing_details(self, /, params_json=None) -> Any: ...
    async def get_public_trades(self, /, params_json=None) -> Any: ...
    async def get_put_call_ratio(self, /, params_json=None) -> Any: ...
    async def get_quote_products(self, /, params_json=None) -> Any: ...
    async def get_quotes(self, /, params_json=None) -> Any: ...
    async def get_recurring_buy_order_details(self, /, params_json) -> Any: ...
    async def get_recurring_buy_order_history(self, /, params_json=None) -> Any: ...
    async def get_recurring_buy_order_list(self, /, params_json=None) -> Any: ...
    async def get_recurring_buy_sub_orders(self, /, params_json) -> Any: ...
    async def get_rfqs(self, /, params_json=None) -> Any: ...
    async def get_saving_balance(self, /, ccy=None) -> Any: ...
    async def get_simulated_margin(self, /, inst_type, incl_real_pos=None, spot_offset_type=None, sim_pos_json=None) -> Any: ...
    async def get_sub_account_borrow_interest_and_limit(self, /, sub_acct=None, ccy=None) -> Any: ...
    async def get_subaccount_balance(self, /, sub_acct) -> Any: ...
    async def get_subaccount_bills(self, /, ccy=None, bill_type=None, sub_acct=None, after=None, before=None, limit=None) -> Any: ...
    async def get_subaccount_funding_balance(self, /, sub_acct, ccy=None) -> Any: ...
    async def get_subaccount_list(self, /, enable=None, sub_acct=None, after=None, before=None, limit=None) -> Any: ...
    async def get_support_coin(self, /) -> Any: ...
    async def get_system_status(self, /, state=None) -> Any: ...
    async def get_system_time(self, /) -> Any: ...
    async def get_taker_flow(self, /, params_json=None) -> Any: ...
    async def get_taker_volume(self, /, params_json=None) -> Any: ...
    async def get_ticker(self, /, inst_id) -> Any: ...
    async def get_tickers(self, /, inst_type, uly=None, inst_family=None) -> Any: ...
    async def get_total_profit_sharing(self, /) -> Any: ...
    async def get_trades(self, /, inst_id, limit=None) -> Any: ...
    async def get_transfer_state(self, /, trans_id, type_) -> Any: ...
    async def get_underlying(self, /, inst_type=None) -> Any: ...
    async def get_unrealized_profit_sharing_details(self, /, params_json=None) -> Any: ...
    async def get_vip_interest_accrued(self, /, ccy=None, ord_id=None, after=None, before=None, limit=None) -> Any: ...
    async def get_vip_interest_deducted(self, /, ccy=None, ord_id=None, after=None, before=None, limit=None) -> Any: ...
    async def get_vip_interest_rate_loan_quota(self, /) -> Any: ...
    async def get_vip_loan_order_detail(self, /, ccy=None, ord_id=None, after=None, before=None, limit=None) -> Any: ...
    async def get_vip_loan_order_list(self, /, ord_id=None, state=None, ccy=None, after=None, before=None, limit=None) -> Any: ...
    async def get_withdrawal_history(self, /, ccy=None, wd_id=None, tx_id=None, state=None, after=None, before=None, limit=None) -> Any: ...
    async def grid_ai_param(self, /, params_json=None) -> Any: ...
    async def grid_amend_order_algo(self, /, payload_json) -> Any: ...
    async def grid_compute_margin_balance(self, /, payload_json) -> Any: ...
    async def grid_margin_balance(self, /, payload_json) -> Any: ...
    async def grid_order_algo(self, /, payload_json) -> Any: ...
    async def grid_orders_algo_details(self, /, params_json) -> Any: ...
    async def grid_orders_algo_history(self, /, params_json=None) -> Any: ...
    async def grid_orders_algo_pending(self, /, params_json=None) -> Any: ...
    async def grid_positions(self, /, params_json=None) -> Any: ...
    async def grid_stop_order_algo(self, /, payload_json) -> Any: ...
    async def grid_sub_orders(self, /, params_json) -> Any: ...
    async def grid_withdraw_income(self, /, payload_json) -> Any: ...
    async def mass_cancel(self, /, request_json) -> Any: ...
    async def one_click_repay(self, /, debt_ccy, repay_ccy) -> Any: ...
    async def order_precheck(self, /, request_json) -> Any: ...
    async def place_algo_order(self, /, inst_id, td_mode, side, ord_type, sz, ccy=None, pos_side=None, reduce_only=None, tgt_ccy=None, algo_cl_ord_id=None, trigger_px=None, order_px=None, trigger_px_type=None, tp_trigger_px=None, tp_ord_px=None, tp_trigger_px_type=None, sl_trigger_px=None, sl_ord_px=None, sl_trigger_px_type=None, callback_ratio=None, callback_spread=None, active_px=None) -> Any: ...
    async def place_batch_orders(self, /, orders) -> Any: ...
    async def place_fix_loan_borrowing_order(self, /, ccy=None, amt=None, max_rate=None, term=None, reborrow=None, reborrow_rate=None) -> Any: ...
    async def place_lead_stop_order(self, /, request_json) -> Any: ...
    async def place_order(self, /, inst_id, td_mode, side, ord_type, sz, px=None, cl_ord_id=None) -> Any: ...
    async def place_recurring_buy_order(self, /, payload_json) -> Any: ...
    async def position_builder(self, /, acct_lv=None, incl_real_pos_and_eq=None, lever=None, greeks_type=None, sim_pos_json=None, sim_asset_json=None) -> Any: ...
    async def purchase_redempt(self, /, ccy, amt, side, rate) -> Any: ...
    async def repay_fix_loan_borrowing_order(self, /, ord_id=None) -> Any: ...
    async def reset_mmp(self, /, request_json) -> Any: ...
    async def reset_subaccount_apikey(self, /, sub_acct, api_key, label, perm=None, ip=None) -> Any: ...
    async def saving_balance(self, /, params_json=None) -> Any: ...
    async def saving_lending_history(self, /, params_json=None) -> Any: ...
    async def saving_public_lending_rate(self, /, params_json=None) -> Any: ...
    async def saving_purchase_redemption(self, /, request_json) -> Any: ...
    async def saving_set_lending_rate(self, /, request_json) -> Any: ...
    async def set_account_level(self, /, acct_lv) -> Any: ...
    async def set_auto_loan(self, /, auto_loan=None) -> Any: ...
    async def set_auto_repay(self, /, auto_repay=None) -> Any: ...
    async def set_greeks(self, /, greeks_type) -> Any: ...
    async def set_isolated_mode(self, /, iso_mode, type_) -> Any: ...
    async def set_lending_rate(self, /, ccy, rate) -> Any: ...
    async def set_leverage(self, /, lever, mgn_mode, inst_id=None, ccy=None, pos_side=None) -> Any: ...
    async def set_marker_instrument(self, /, request_json) -> Any: ...
    async def set_mmp_config(self, /, request_json) -> Any: ...
    async def set_permission_transfer_out(self, /, sub_acct, can_trans_out) -> Any: ...
    async def set_position_mode(self, /, pos_mode) -> Any: ...
    async def set_risk_offset_type(self, /, type_) -> Any: ...
    async def set_sub_accounts_vip_loan(self, /, enable, alloc_json) -> Any: ...
    async def simple_earn_amend_lending_order(self, /, request_json) -> Any: ...
    async def simple_earn_get_lending_apy_history(self, /, params_json=None) -> Any: ...
    async def simple_earn_get_lending_offers(self, /, params_json=None) -> Any: ...
    async def simple_earn_get_lending_orders_list(self, /, params_json=None) -> Any: ...
    async def simple_earn_get_lending_sub_orders(self, /, params_json=None) -> Any: ...
    async def simple_earn_get_pending_lending_volume(self, /, params_json=None) -> Any: ...
    async def simple_earn_place_lending_order(self, /, request_json) -> Any: ...
    async def spot_borrow_repay_history(self, /, ccy=None, type_=None, after=None, before=None, limit=None) -> Any: ...
    async def spot_manual_borrow_repay(self, /, ccy=None, side=None, amt=None) -> Any: ...
    async def spread_cancel_all_orders(self, /, payload_json) -> Any: ...
    async def spread_cancel_order(self, /, payload_json) -> Any: ...
    async def spread_get_active_orders(self, /, params_json=None) -> Any: ...
    async def spread_get_order_book(self, /, params_json) -> Any: ...
    async def spread_get_order_details(self, /, params_json) -> Any: ...
    async def spread_get_orders(self, /, params_json=None) -> Any: ...
    async def spread_get_public_trades(self, /, params_json) -> Any: ...
    async def spread_get_spreads(self, /, params_json=None) -> Any: ...
    async def spread_get_ticker(self, /, params_json) -> Any: ...
    async def spread_get_trades(self, /, params_json=None) -> Any: ...
    async def spread_place_order(self, /, payload_json) -> Any: ...
    async def stop_recurring_buy_order(self, /, payload_json) -> Any: ...
    async def subaccount_transfer(self, /, ccy, amt, froms, to, from_sub_account, to_sub_account) -> Any: ...
    async def withdrawal(self, /, ccy, amt, dest, to_addr, fee, chain=None, area_code=None, client_id=None) -> Any: ...
    async def withdrawal_lightning(self, /, ccy, invoice, memo) -> Any: ...

@final
class WsClient:
    def __new__(cls, /) -> "WsClient": ...
    def __init__(self, /) -> None: ...

    async def __aiter__(self, /) -> Any: ...
    async def __anext__(self, /) -> Any: ...
    async def close(self, /) -> Any: ...
    @staticmethod
    async def connect_private(config, max_reconnect_attempts=None) -> Any: ...
    @staticmethod
    async def connect_public(config, max_reconnect_attempts=None) -> Any: ...
    async def is_connected(self, /) -> Any: ...
    async def reconnect(self, /) -> Any: ...
    async def recv(self, /) -> Any: ...
    async def subscribe_account(self, /, ccy=None) -> Any: ...
    async def subscribe_algo_advance(self, /, inst_type=None, inst_family=None, inst_id=None) -> Any: ...
    async def subscribe_algo_recurring_buy(self, /, algo_id=None) -> Any: ...
    async def subscribe_balance_and_position(self, /) -> Any: ...
    async def subscribe_block_tickers(self, /, inst_family=None) -> Any: ...
    async def subscribe_candles(self, /, inst_id, interval='1m') -> Any: ...
    async def subscribe_funding_rate(self, /, inst_id) -> Any: ...
    async def subscribe_grid_orders_contract(self, /, algo_id=None, inst_id=None) -> Any: ...
    async def subscribe_grid_orders_moon(self, /, algo_id=None, inst_id=None) -> Any: ...
    async def subscribe_grid_orders_spot(self, /, algo_id=None, inst_id=None) -> Any: ...
    async def subscribe_grid_positions(self, /, algo_id=None, inst_type=None, inst_id=None) -> Any: ...
    async def subscribe_grid_sub_orders(self, /, algo_id=None, inst_id=None) -> Any: ...
    async def subscribe_index_tickers(self, /, inst_id) -> Any: ...
    async def subscribe_mark_price(self, /, inst_id) -> Any: ...
    async def subscribe_orderbook(self, /, inst_id) -> Any: ...
    async def subscribe_orderbook5(self, /, inst_id) -> Any: ...
    async def subscribe_orderbook50_l2_tbt(self, /, inst_id) -> Any: ...
    async def subscribe_orderbook_l2_tbt(self, /, inst_id) -> Any: ...
    async def subscribe_orders(self, /, inst_type, inst_id=None) -> Any: ...
    async def subscribe_orders_algo(self, /, inst_type, inst_family=None, inst_id=None) -> Any: ...
    async def subscribe_positions(self, /, inst_type, inst_id=None) -> Any: ...
    async def subscribe_public_block_trades(self, /, inst_family=None) -> Any: ...
    async def subscribe_public_struc_block_trades(self, /, inst_family=None) -> Any: ...
    async def subscribe_quotes(self, /, inst_family=None) -> Any: ...
    async def subscribe_rfqs(self, /, inst_family=None) -> Any: ...
    async def subscribe_struc_block_trades(self, /, inst_family=None) -> Any: ...
    async def subscribe_tickers(self, /, inst_id) -> Any: ...
    async def subscribe_trades(self, /, inst_id) -> Any: ...
    async def subscription_count(self, /) -> Any: ...

@final
class Balance:
    total_eq: str
    iso_eq: str
    mgn_ratio: str
    details: list[BalanceDetail]

    def __new__(cls, /) -> "Balance": ...
    def __init__(self, /) -> None: ...


@final
class BalanceDetail:
    ccy: str
    eq: str
    avail_bal: str
    frozen_bal: str

    def __new__(cls, /) -> "BalanceDetail": ...
    def __init__(self, /) -> None: ...


@final
class Position:
    inst_id: str
    pos_side: str
    pos: str
    avg_px: str
    upl: str
    lever: str

    def __new__(cls, /) -> "Position": ...
    def __init__(self, /) -> None: ...


@final
class Order:
    ord_id: str
    cl_ord_id: str
    inst_id: str
    side: str
    ord_type: str
    state: str
    px: str
    sz: str
    acc_fill_sz: str
    avg_px: str

    def __new__(cls, /) -> "Order": ...
    def __init__(self, /) -> None: ...


@final
class Ticker:
    inst_id: str
    last: str
    ask_px: str
    bid_px: str
    high_24h: str
    low_24h: str
    vol_24h: str

    def __new__(cls, /) -> "Ticker": ...
    def __init__(self, /) -> None: ...

